// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pass

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupPassPassword(ctx *pulumi.Context, args *LookupPassPasswordArgs, opts ...pulumi.InvokeOption) (*LookupPassPasswordResult, error) {
	var rv LookupPassPasswordResult
	err := ctx.Invoke("pass:index/getPassPassword:getPassPassword", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPassPassword.
type LookupPassPasswordArgs struct {
	Path string `pulumi:"path"`
}

// A collection of values returned by getPassPassword.
type LookupPassPasswordResult struct {
	Body string                 `pulumi:"body"`
	Data map[string]interface{} `pulumi:"data"`
	Full string                 `pulumi:"full"`
	// The provider-assigned unique ID for this managed resource.
	Id       string `pulumi:"id"`
	Password string `pulumi:"password"`
	Path     string `pulumi:"path"`
}
