// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("pass");

/**
 * Whether or not call `pass git pull`.
 */
export let refreshStore: boolean | undefined = __config.getObject<boolean>("refreshStore") || true;
/**
 * Password storage directory to use.
 */
export let storeDir: string | undefined = __config.get("storeDir") || utilities.getEnv("PASSWORD_STORE_DIR");
