// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi/config"
)

// Whether or not call `pass git pull`.
func GetRefreshStore(ctx *pulumi.Context) bool {
	v, err := config.TryBool(ctx, "pass:refreshStore")
	if err == nil {
		return v
	}
	return true
}

// Password storage directory to use.
func GetStoreDir(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "pass:storeDir")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "PASSWORD_STORE_DIR").(string)
}
