// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPassPassword(args: GetPassPasswordArgs, opts?: pulumi.InvokeOptions): Promise<GetPassPasswordResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("pass:index/getPassPassword:getPassPassword", {
        "path": args.path,
    }, opts);
}

/**
 * A collection of arguments for invoking getPassPassword.
 */
export interface GetPassPasswordArgs {
    readonly path: string;
}

/**
 * A collection of values returned by getPassPassword.
 */
export interface GetPassPasswordResult {
    readonly body: string;
    readonly data: {[key: string]: any};
    readonly full: string;
    readonly password: string;
    readonly path: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
